sudo: required

dist: trusty
language: node_js
node_js:
  - "10.3.0"

cache:
  directories:
    - client/node_modules
    - server/node_modules

services:
  - docker

script: node misc/run-all-test.js
